# This file was generated by GoReleaser. DO NOT EDIT.
class Kubecli < Formula
  desc "kubecli --help"
  homepage "http://docs.codefresh.io"
  version "0.0.11"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/verchol/kubecli/releases/download/v0.0.11/kubecli_0.0.11_Darwin_x86_64.tar.gz"
    sha256 "23f9f2a756f2cbc9252686839209485e5b31056c1edbfca598e1a64e0f793f00"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/verchol/kubecli/releases/download/v0.0.11/kubecli_0.0.11_Linux_x86_64.tar.gz"
      sha256 "55097c1cf672882a1a9fd6b3e7a13bc0544b724705077eb613166139daea9732"
    end
  end

  def install
    bin.install "kubecli"
  end
end
